apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: teststack1100
spec:
  metrics:
    - name: teststack1100
      provider:
        opsmx:
          profile: "opsmx-profile"
          gateUrl: https://oes-argoqa.isd-dev.opsmx.net/
          user: user2
          application: stackdriveranalysistest1
          baselineStartTime: "2022-09-16T06:10:00Z"
          canaryStartTime: "2022-09-19T08:06:00Z"
          lifetimeMinutes: 04
          threshold: 
            pass: 80
            marginal: 60
          services:
          - logTemplateName: teststack1
            logScopeVariables: "resource.labels.container_name"
            baselineLogScope: "issuegen-prod"
            canaryLogScope: "issuegen-prod"

