apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testapp
spec:
  metrics:
    - name: testapp
      provider:
        opsmx:
          profile: "opsmx-profile"
          gateUrl: https://argoqa-helm.isd-dev.opsmx.net/
          user: user2
          application: stackanalysistest1
          baselineStartTime: "2022-09-16T06:10:00Z"
          canaryStartTime: "2022-09-19T08:06:00Z"
          lifetimeMinutes: 03
          threshold: 
            pass: 80
            marginal: 60
          services:
          - logTemplateName: logtemp1
            logScopeVariables: "resource.labels.container_name"
            baselineLogScope: "issuegen-prod"
            canaryLogScope: "issuegen-prod"

